sudo: require
language: cpp
os: osx
compiler: gcc

deploy:
 provider: releases
 api_key: $API_KEY
 file: Build/build.zip
 skip_cleanup: true
 draft: true

addons:
 homebrew:
  update: true
  packages:
  - qt

before_install:
 - export PATH="/usr/local/opt/qt/bin:$PATH"
before_script:
 - mkdir Build
 - cd Build
script:
 - qmake ../Source
 - make
 - zip -r build.zip CourseWork_EnglishTests.app
